### ISSUE TITLE
Inference FPS on video?

### ISSUE THREAD

**Issue by sanjeevnara7** [AndreyGermanov/yolov8_inference_video_javascript#1]
Great work on this repo! I would like to know what FPS you are able to achieve during inference on the video? 

My experiments with ORT web only give me 500ms/per image with the YOLOv8 which is really low (like 2fps?). I am interested in achieving 20+ fps on an input mp4 video, do you have any ideas?

Best regards

**Comment by AndreyGermanov** [comment]
I have similar results. Sometimes 400ms per image, sometimes 934ms. It depends on CPU power. Not sure that without GPU is possible to achieve much better results than you achieved.

Currently, I am discovering DeepSparse technology, which is aimed to run models on CPU with GPU speed.(https://docs.neuralmagic.com/).

Will share results in case of success.

**Comment by sanjeevnara7** [comment]
Hi @AndreyGermanov thanks for your response. Using TensorflowJS with YOLOv8, I'm actually able to get 17fps with WebGL, while ORT web still only gives me 2fps (I also checked if WebGL is being used in the backend). Not sure if this is an issue with the library, since I'm running on an m1 mac. 

Deepsparse gives me 15ms inference per image on an 8-core CPU which is very promising! 

Best regards
