### ISSUE TITLE
detection dont work on browser

### ISSUE THREAD

**Issue by chih3b** [AndreyGermanov/yolov8_inference_video_javascript#4]
first of all thank you for beging so helpful.i have a problem.i downloaded your code and tried to run it with webserver exetention in vscode but only the video work with no detections and when i clicked inspect elements in the browser i got this error:Error: no available backend found. ERR: [wasm] RuntimeError: indirect call to null, [cpu] Error: previous call to 'initializeWebAssembly()' failed., [xnnpack] Error: previous call to 'initializeWebAssembly()' failed.

**Comment by AndreyGermanov** [comment]
From time to time, Microsoft updates the ONNX runtime library without worrying about backward compatibility. To solve it, ensure that the version of the "ort.min.js" that you import matches the version of "ort-wasm-simd.wasm" binary that you downloaded. Do the following:

1. Download the last ort-wasm-simd.wasm file from here: https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort-wasm-simd.wasm

2. Ensure that you load the last version of the "ort.min.js". The first line of the "worker.js" should be:

```javascript
importScripts("https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.min.js");
```

3. Perhaps, you will need to restart live server to apply these changes.

**Comment by chih3b** [comment]
Thank you so much it worked but i still have 2 problems.i tried using my webcam and its very slow.how can we optimize it?i want to count detections after they pass a line(i did that in oython with opencv when i was using flask before i saw your solution) how can put that logic in your solution?thank you

**Comment by AndreyGermanov** [comment]
Hi, not sure how you can dramatically increase the YOLOv8 inference speed without GPU.

To count detections that passed a line, you can use a simple geometry. If you have coordinates of the detected box [x1,y1,x2,y2] for each frame and if you have coordinates of the line [x1,y1,x2,y2], you can calculate the intersection and see if the detected box passed it or not.

**Comment by eyaler** [comment]
instead of downloading the wasm you can do:
```
importScripts('https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.wasm-core.min.js')
ort.env.wasm.wasmPaths = 'https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/'
```
