### ISSUE TITLE
InferenceSession on GPU ?

### ISSUE THREAD

**Issue by shimaamorsy** [AndreyGermanov/yolov8_inference_video_javascript#5]
How to inferenceSession on GPU ?

**Comment by AndreyGermanov** [comment]
Using GPU with YoloV8 in a web browser is not stable now. The "webgl" execution provider that previously used for GPU  in the web browser does not work with YoloV8 (as described in the article).

But, there is a special ONNX runtime version, in which you can try to use the "webgpu" execution provider:

```javascript
importScripts("https://cdn.jsdelivr.net/npm/onnxruntime-web@1.17.1/dist/ort.webgpu.min.js");
.
.
.
model = await ort.InferenceSession.create("./yolov8n.onnx",{ executionProviders: ['webgpu'] });
```

However, it works only in modern browsers, that support WebGPU.

Read more in this issue: https://github.com/microsoft/onnxruntime/issues/19779
